# Likely have to change the directory.
setwd("~/Documents/courses/spring-2017/big-data/bigDataProject/R/part-2/age-hypothesis/")

library(tidyverse)
library(stringr)
library(sparklyr)
library(magrittr)
library(ggmap)

complaints <- read_csv(file = "../../../data/311-reduced.csv")
names(complaints) %<>% make.names

only.noise <-
  complaints %>%
  filter(Complaint.Type %>% str_to_lower %>% str_detect(., "noise"))

nyc <- 
  get_map(location = "new york city", color = "bw") %>%
  ggmap +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

## Plot 1: All heat on NYC map.

nyc.noise.heatmap <-
  nyc +
    stat_density2d(
      aes(x = Longitude, y = Latitude,
          fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = only.noise
    ) +
    scale_fill_gradient(low = "gold", high = "red") +
    labs(
      title = "Heatmap of noise complaints across NYC",
      caption = "Plot generated by explore-age.R"
    ) +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

# Takes a minute or two.
ggsave(nyc.noise.heatmap, filename = "nyc-noise-heatmap.png", device = "png",
       path = "output/", height = 8, width = 8, units = "in")

## Plot 2: All heat on NYC map, facet by month.

monthly.noise.complaints <-
  only.noise %>%
  mutate(
    month = 
      lubridate::parse_date_time(Created.Date, orders = "mdy HMS") %>% 
      lubridate::month(., label = TRUE, abbr = TRUE) %>%
      as.factor
  )

nyc.monthly.noise <-
  nyc +
    facet_wrap(~ month, ncol = 4) + 
    stat_density2d(
      aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = monthly.noise.complaints
    ) +
    scale_fill_gradient(low = "blue", high = "red") +
    labs(
      title = "Noise complaints across NYC over the year",
      caption = "Plot generated by explore-age.R"
    ) +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

# Takes a minute or two.
ggsave(nyc.monthly.noise, filename = "nyc-monthly-noise.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")

### Plot 2.5: Line plot of noise complaints by month.
monthly.noise.line.plot <-
  monthly.noise.complaints %>%
  select(Borough, month) %>%
  filter(Borough != "None") %>%
  group_by(Borough, month) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  mutate(Borough = Borough %>% str_to_title %>% as.factor) %>%
  ggplot(aes(x = month, y = count, group = Borough, color = Borough)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = scales::comma) +
    labs(
      x = "Month of Year",
      y = "Heating complaint frequency",
      title = "Heating complaints over the year",
      caption = "Plot generated by explore-age.R"
    ) +
    theme(
      legend.position = c(0.7875, 0.8),
      legend.title = element_blank()
    )
  
ggsave(monthly.noise.line.plot, filename = "monthly-heat-line.png", 
       device = "png", path = "output/", height = 9, width = 9, units = "in")
    

### Plot 3: Income vs Heating complaint frequency

census.age <- read_csv("./data/census_age.csv")
names(census.age) %<>% make.names
census.age <- census.age %>% mutate(ZIP = ZIP.Loc.Code %>% as.factor)

binned.census.age <-
  census.age %>% 
  select(ZIP, Total, 8:26, 32:50) %>%
  transmute(
    ZIP = ZIP %>% as.factor,
    total = Total,
    total.millenial    = rowSums(.[, 3:7]) + rowSums(.[, 22:26]),
    total.gen.x        = rowSums(.[, 8:12]) + rowSums(.[, 27:31]),
    total.baby.boomers = rowSums(.[, 13:21]) + rowSums(.[, 32:40])
  ) %>%
  select(ZIP, total.millenial, total.gen.x, total.baby.boomers) %>%
  mutate(
    percent.millenial = total.millenial / (total.millenial + total.gen.x + total.baby.boomers)
  ) %>%
  arrange(percent.millenial %>% desc)

grouped.noise.zip <-
  only.noise %>%
  filter(Borough != 'None') %>%
  select(ZIP = Incident.Zip, Borough) %>%
  mutate_at(.cols = vars(ZIP, Borough),
            .funs = funs(as.factor)) %>%
  group_by(Borough, ZIP) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  inner_join(., y = binned.census.age, by = "ZIP") %>%
  mutate(
    normalized.count = count / (total.millenial + total.gen.x + total.baby.boomers)
  ) %>%
  arrange(percent.millenial %>% desc)

## Plot noise by zip

noise.by.zip.plot <-
  grouped.noise.zip %>%
  mutate(
    Borough = Borough %>% str_to_title
  ) %>%
  ggplot(aes(x = percent.millenial, y = normalized.count)) +
    geom_point() +
    # geom_smooth(method=lm) +
    # facet_grid(Borough ~ .) +
    scale_x_continuous(labels = scales::percent) +
    guides(color = F, alpha = F) +
    labs(
      x = "Percent of ZIP considered millennial",
      y = "Noise complaints per resident",
      title = "Millennial percent vs noise complaint frequency",
      caption = "Plot generated by explore-age.R"
    ) + 
    theme(panel.grid.minor = element_blank())

ggsave(noise.by.zip.plot, filename = "millennial-zip-noise.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")
