# Likely have to change the directory.
setwd("~/Documents/courses/spring-2017/big-data/bigDataProject/R/part-2/heat-hypothesis/")

library(tidyverse)
library(stringr)
library(sparklyr)
library(magrittr)
library(ggmap)

# Setup Spark configuration
# config <- spark_config()
# config$spark.local.dir <- "/Volumes/D128G/tmp"
# sc <- spark_connect(master = "local", config = config, version="2.0.1")
# all.data <- sparklyr::spark_read_csv(sc = sc, name = "data", path = "~/Downloads/311-all.csv",
#                                      header = TRUE, infer_schema = TRUE, memory = FALSE, 
#                                      overwrite = TRUE)

complaints <- read_csv(file = "../../../data/311-reduced.csv")
names(complaints) %<>% make.names

only.heat <-
  complaints %>%
  filter(Complaint.Type %>% str_to_lower %>% str_detect(., "heat"))

nyc <- 
  get_map(location = "new york city", color = "bw") %>%
  ggmap +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

## Plot 1: All heat on NYC map.

nyc.heatmap <-
  nyc +
    stat_density2d(
      aes(x = Longitude, y = Latitude,
          fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = only.heat
    ) +
    scale_fill_gradient(low = "gold", high = "red") +
    labs(
      title = "Heatmap of heating complaints across NYC",
      caption = "Plot generated by explore-heat.R"
    ) +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

# Takes a minute or two.
ggsave(nyc.heatmap, filename = "nyc-heating-heatmap.png", device = "png",
       path = "output/", height = 8, width = 8, units = "in")

## Plot 2: All heat on NYC map, facet by month.

monthly.heat.complaints <-
  only.heat %>%
  mutate(
    month = 
      lubridate::parse_date_time(Created.Date, orders = "mdy HMS") %>% 
      lubridate::month(., label = TRUE, abbr = TRUE) %>%
      as.factor
  )

nyc.monthly.heat <-
  nyc +
    facet_wrap(~ month, ncol = 4) + 
    stat_density2d(
      aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = monthly.heat.complaints
    ) +
    scale_fill_gradient(low = "blue", high = "red") +
    labs(
      title = "Heating complaints across NYC",
      caption = "Plot generated by explore-heat.R"
    ) +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

# Also takes a minute or two.
ggsave(nyc.monthly.heat, filename = "nyc-monthly-heating.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")

### Plot 2.5: Line plot of heat complaints by month.
monthly.heat.line.plot <-
  monthly.heat.complaints %>%
  select(Borough, month) %>%
  filter(Borough != "None") %>%
  group_by(Borough, month) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  mutate(Borough = Borough %>% str_to_title %>% as.factor) %>%
  ggplot(aes(x = month, y = count, group = Borough, color = Borough)) +
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = scales::comma) +
    labs(
      x = "Month of Year",
      y = "Heating complaint frequency",
      title = "Heating complaints over the year",
      caption = "Plot generated by explore-heat.R"
    ) +
    theme(
      legend.position = c(0.5, 0.85),
      legend.title = element_blank()
    )
  
ggsave(monthly.heat.line.plot, filename = "monthly-heat-line.png", 
       device = "png", path = "output/", height = 8, width = 8, units = "in")
    

### Plot 3: Income vs Heating complaint frequency

census.income <- read_csv("./data/census_income.csv")
names(census.income) <- c('ZIP', 'Median.Income.2015')
census.income <- census.income %>% mutate(ZIP = ZIP %>% as.factor)

census.pop <- read_csv("./data/census_age.csv")
names(census.pop) %<>% make.names
census.pop <- census.pop %>% select(ZIP.Loc.Code, Total) %>% mutate(ZIP = ZIP.Loc.Code %>% as.factor)


heat.by.zip <-
  only.heat %>%
  transmute(ZIP = Incident.Zip %>% as.factor) %>%
  group_by(ZIP) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  inner_join(., y = census.income, by = "ZIP") %>%
  inner_join(., y = census.pop, by = "ZIP") %>%
  transmute(
    ZIP = ZIP %>% as.factor,
    income = Median.Income.2015,
    total.population = Total,
    heating.complaints = count,
    heating.complaints.normalized = heating.complaints / total.population
  )

heat.by.zip.plot <-
  heat.by.zip %>%
  ggplot(aes(x = heating.complaints.normalized, y = income)) +
    geom_point() +
    scale_y_continuous(labels = scales::dollar) +
    scale_x_continuous(labels = scales::comma) +
    labs(
      y = "Median income",
      x = "Complaints per person",
      title = "Income vs heating complaint frequency",
      caption = "Plot generated by explore-heat.R"
    ) +
    theme(panel.grid.minor.x = element_blank()) +
    coord_flip()

ggsave(heat.by.zip.plot, filename = "zip-income-count.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")

## Plot 4: ZIP GDP vs Heating complaint frequency

# TODO: should x be count? Or Count normalized by __ ?

census.gdp = read_csv("./data/census_gdp.csv")
names(census.gdp) <- c("ZIP", "GDP")
census.gdp %<>% mutate(ZIP = ZIP %>% as.numeric)

heat.by.zip.gdp.plot <-
  heat.by.zip %>%
  inner_join(., y = census.gdp, by = "ZIP") %>%
  ggplot(aes(x = count, y = GDP, label = ZIP %>% as.character)) +
    geom_point() +
    scale_y_continuous(labels = scales::dollar) +
    scale_x_continuous(labels = scales::comma) +
    labs(
      y = "Zipcode GDP",
      x = "Total complaints per Zipcode",
      title = "Per-capita Income vs Complaint",
      caption = "Plot generated by explore-heat.R"
    ) +
    theme(panel.grid.minor = element_blank()) +
    coord_flip()
  
ggsave(heat.by.zip.gdp.plot, filename = "zip-gdp-count.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")
