setwd("~/Documents/courses/spring-2017/big-data/bigDataProject/R/")

library(tidyverse)
library(stringr)
library(sparklyr)

# Setup Spark configuration
config <- spark_config()
sc <- spark_connect(master = "local", config = config, version="2.0.1")

all.data <- sparklyr::spark_read_csv(sc = sc, name = "data", path = "~/Downloads/311-all.csv",
                                     header = TRUE, infer_schema = TRUE, memory = FALSE, 
                                     overwrite = TRUE)

# Frequency table of <complaint, count> aggregated across all boroughs.
complaints <-
  all.data %>%
  select(Complaint_Type) %>%
  group_by(Complaint_Type) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  collect

not.aggregated.plot <-
  complaints %>%
  mutate(
    Complaint_Type = Complaint_Type %>% str_to_title,
    percent = count / sum(count)  
  ) %>%
  arrange(count %>% desc) %>%
  filter(row_number() <= 25) %>%
  ggplot(mapping = aes(x = reorder(Complaint_Type, percent), y = percent, fill = percent)) +
    geom_bar(stat = "identity", width = 0.575) +
    scale_fill_gradient(low = "beige", high = "firebrick", guide = "none") +
    scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.12, 0.03)) +
    labs(
      x = "Complaint type", 
      y = "City-wide complaint prominence (by percent)",
      caption = "Plot generated by part-1-plots.R"
    ) +
    theme(panel.grid.minor = element_blank()) +
    coord_flip()

ggsave(not.aggregated.plot, height = 8, width = 7, 
       units = "in", device = "png", path = "part-1/",
       filename = "complaints-total-not-aggregated.png")


aggregated.plot <-
  complaints %>%
  
  # Group similar complaint types together and convert to titlecase.
  mutate(
    Complaint_Type =
      ifelse(Complaint_Type %>% str_to_lower %>% str_detect("heat"),
             yes = "Aggregate Heat", no =
               ifelse(Complaint_Type %>% str_to_lower %>% str_detect("noise"),
                      yes = "Aggregate Noise", no =
                        ifelse(Complaint_Type %>% str_to_lower %>% str_detect("street"),
                               yes = "Aggregate street", no = Complaint_Type)
                      )
      ) %>% str_to_title
  ) %>%
  
  # Re-group our complaints to aggregate cleaned complaint types, compute new counts.
  group_by(Complaint_Type) %>%
    summarize(count = sum(count)) %>%
    ungroup() %>%
  mutate(percent = count / sum(count)) %>%
  
  # Isolate top 25 complaint types.
  arrange(count %>% desc) %>%
  filter(row_number() <= 25) %>%
  
  # Plot.
  ggplot(mapping = aes(x = reorder(Complaint_Type, percent), y = percent, fill = percent)) +
    geom_bar(stat = "identity", width = 0.575) +
    scale_fill_gradient(low = "beige", high = "firebrick", guide = "none") +
    scale_y_continuous(labels = scales::percent, breaks = seq(0, 0.15, 0.03)) +
    labs(
      x = "Complaint type", 
      y = "City-wide complaint prominence (by percent)",
      caption = "Plot generated by part-1-plots.R"
    ) +
    theme(panel.grid.minor = element_blank()) +
    coord_flip()

ggsave(aggregated.plot, height = 8, width = 7, 
       units = "in", device = "png", path = "part-1/",
       filename = "complaints-total-aggregated.png")

complaints.agg.data <-
  complaints %>%
  
  # Group similar complaint types together and convert to titlecase.
  mutate(
    Complaint_Type =
      ifelse(Complaint_Type %>% str_to_lower %>% str_detect("heat"),
             yes = "Aggregate Heat", no =
               ifelse(Complaint_Type %>% str_to_lower %>% str_detect("noise"),
                      yes = "Aggregate Noise", no =
                        ifelse(Complaint_Type %>% str_to_lower %>% str_detect("street"),
                               yes = "Aggregate street", no = Complaint_Type)
               )
      ) %>% str_to_title
  ) %>%
  
  # Re-group our complaints to aggregate cleaned complaint types, compute new counts.
  group_by(Complaint_Type) %>%
    summarize(count = sum(count)) %>%
    ungroup() %>%
  mutate(percent = count / sum(count))


# Top 25 complaints account for 70% of all complaints.
top.25.complaints <-
  complaints.agg.data %>%
  arrange(count %>% desc) %>%
  filter(row_number() <= 25) %>%
  .[["Complaint_Type"]]


# TODO: MUST RE-RUN CHARLIE'S SCRIPT TO REDUCE UNSPECIFIED's.
complaints.across.boroughs <-
  all.data %>%
  select(Complaint_Type, Borough) %>%
  group_by(Borough, Complaint_Type) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  collect %>%

  # Group similar complaint types together and convert to titlecase.
  mutate(
    Complaint_Type = 
      ifelse(Complaint_Type %>% str_to_lower %>% str_detect("heat"),
             yes = "Aggregate Heat", no = 
               ifelse(Complaint_Type %>% str_to_lower %>% str_detect("noise"),
                      yes = "Aggregate Noise", no = 
                        ifelse(Complaint_Type %>% str_to_lower %>% str_detect("street"),
                               yes = "Aggregate street", no = Complaint_Type)
               )
      ) %>% str_to_title
  ) %>%
  
  # Re-group our complaints to aggregate cleaned complaint types, compute new counts.
  group_by(Borough, Complaint_Type) %>%
    summarize(count = sum(count)) %>%
    ungroup() %>%
  
  filter(Complaint_Type %in% top.25.complaints)
  

complaints.across.boroughs.plot <-
  complaints.across.boroughs %>%
  arrange(count %>% desc) %>%
  mutate_at(
    .cols = vars(Borough, Complaint_Type),
    .funs = funs(. %>% str_to_title %>% as.factor)
  ) %>%
  mutate(percent = count / sum(count)) %>%
  ggplot(mapping = aes(x = Complaint_Type, y = percent, fill = Complaint_Type)) +
    geom_bar(stat = "identity", width = 0.575) +
    facet_grid(Borough ~ .) +
    scale_y_continuous(labels = scales::percent, breaks = c(0.02, 0.04, 0.06)) +
    labs(
      x = "Complaint Type",
      y = "Percent per borough",
      title = "Top 25 overall complaints, by borough",
      caption = "Plot generated by part-1-plots.R"
    ) +
    theme(
      axis.text.x = element_text(angle = 50, hjust = 1),
      panel.grid.minor = element_blank(),
      legend.position = "none",
      legend.title = element_blank()
    )

ggsave(complaints.across.boroughs.plot, height = 9, width = 8,
       units = "in", device = "png", path = "part-1/",
       filename = "aggregated-complaints-by-borough.png")

