# Likely have to change the directory.
setwd("~/Documents/courses/spring-2017/big-data/bigDataProject/R/part-2/heat-hypothesis/")

library(tidyverse)
library(stringr)
library(sparklyr)
library(magrittr)
library(ggmap)

# Setup Spark configuration
# config <- spark_config()
# config$spark.local.dir <- "/Volumes/D128G/tmp"
# sc <- spark_connect(master = "local", config = config, version="2.0.1")
# all.data <- sparklyr::spark_read_csv(sc = sc, name = "data", path = "~/Downloads/311-all.csv",
#                                      header = TRUE, infer_schema = TRUE, memory = FALSE, 
#                                      overwrite = TRUE)

complaints <- read_csv(file = "~/Downloads/311-reduced/311-reduced.csv")
names(complaints) %<>% make.names

##

only.heat <-
  complaints %>%
  filter(Complaint.Type %>% str_to_lower %>% str_detect(., "heat"))

nyc <- 
  get_map(location = "new york city", color = "bw") %>%
  ggmap +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

nyc.heatmap <-
  nyc +
    stat_density2d(
      aes(x = Longitude, y = Latitude,
          fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = only.heat
    ) +
    scale_fill_gradient(low = "gold", high = "red") +
    labs(
      title = "Heatmap of heating complaints across NYC",
      caption = "Plot generated by initial-exploration.R") +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

ggsave(nyc.heatmap, filename = "nyc-heating-heatmap.png", device = "png",
       path = "output/", height = 8, width = 8, units = "in")

##

monthly.heat.complaints <-
  complaints %>%
  filter(Complaint.Type %>% str_to_lower %>% str_detect(., "heat")) %>%
  mutate(
    month = 
      lubridate::parse_date_time(Created.Date, orders = "mdy HMS") %>% 
      lubridate::month(., label = TRUE, abbr = FALSE) %>%
      as.factor
  )

nyc.monthly.heat <-
  nyc +
    facet_wrap(~ month, ncol = 4) + 
    stat_density2d(
      aes(x = Longitude, y = Latitude, fill = ..level.., alpha = ..level..), 
      geom = "polygon", data = monthly.heat.complaints
    ) +
    scale_fill_gradient(low = "blue", high = "red") +
    labs(title = "Heating complaints across NYC") +
    theme(
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      legend.position = "none"
    )

ggsave(nyc.monthly.heat, filename = "nyc-monthly-heating.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")

### 

census.income <- read_csv("./data/census_income.csv")
names(census.income) <- c('ZIP', 'Median.Income.2015')
census.income <- census.income %>% mutate(ZIP = ZIP %>% as.numeric)


heat.by.zip <-
  only.heat %>%
  transmute(ZIP = Incident.Zip) %>%
  group_by(ZIP) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  inner_join(., y = census.income, by = "ZIP")

heat.by.zip.plot <-
  heat.by.zip %>%
  ggplot(aes(x = count, y = Median.Income.2015, label = ZIP %>% as.character)) +
    geom_point() +
    scale_y_continuous(labels = scales::dollar) +
    scale_x_continuous(labels = scales::comma) +
    coord_flip() +
    labs(
      x = "Median income",
      y = "Total complaints per ZIP",
      title = "Income vs Complaint Frequency",
      caption = "Plot generated by initial-exploration.R"
    ) +
    theme(panel.grid.minor = element_blank())

ggsave(heat.by.zip.plot, filename = "zip-income-count.png", device = "png",
       path = "output/", height = 9, width = 9, units = "in")

heat.by