library(tidyverse)
library(stringr)
library(sparklyr)

# Setup Spark configuration
config <- spark_config()
config$spark.local.dir <- "/Volumes/D128G/tmp"
sc <- spark_connect(master = "local", config = config, version="2.0.1")

all.data <- sparklyr::spark_read_csv(sc = sc, name = "data", path = "~/Downloads/311-all.csv",
                                     header = TRUE, infer_schema = TRUE, memory = FALSE, 
                                     overwrite = TRUE)

# Frequency plot of complaints across all boroughs.
complaints <-
  all.data %>%
  select(Complaint_Type) %>%
  group_by(Complaint_Type) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  collect

complaints.plot <-
  complaints %>%
  arrange(count %>% desc) %>%
  filter(row_number() <= 25) %>%
  mutate(
    percent = count / sum(count),
    Complaint_Type = stringr::str_to_title(Complaint_Type)  
  ) %>%
  ggplot(mapping = aes(x = reorder(Complaint_Type, percent), y = percent, fill = percent)) +
    geom_bar(stat = "identity", width = 0.575) +
    scale_fill_gradient(low = "beige", high = "firebrick", guide = "none") +
    scale_y_continuous(labels = scales::percent) +
    labs(
      x = "Complaint type", 
      y = "Complaint prominence by percent",
      caption = "Plot generated by part-1-plots.R"
    ) +
    theme(
      panel.grid.minor.y = element_blank(),
      panel.grid.minor.x = element_blank()
    ) +
    coord_flip()

ggsave(complaints.plot, height = 8, width = 7, 
       units = "in", device = "png", path = ".",
       filename = "complaints-total.png")

# Top 25 complaints account for 70% of all complaints.
top.25.complaints <-
  complaints %>%
  arrange(count %>% desc) %>%
  filter(row_number() <= 25) %>%
  .[["Complaint_Type"]]

complaints.across.boroughs <-
  all.data %>%
  select(Complaint_Type, Borough) %>%
  filter(Complaint_Type %in% top.25.complaints) %>%
  group_by(Borough, Complaint_Type) %>%
    summarize(count = n()) %>%
    ungroup() %>%
  collect

complaints.across.boroughs.plot <-
  complaints.across.boroughs %>%
  arrange(count %>% desc) %>%
  mutate_at(
    .cols = vars(Borough, Complaint_Type),
    .funs = funs(. %>% str_to_title %>% as.factor)
  ) %>%
  mutate(percent = count / sum(count)) %>%
  ggplot(mapping = aes(x = Complaint_Type, y = percent, fill = Complaint_Type)) +
    geom_bar(stat = "identity", width = 0.575) +
    facet_grid(Borough ~ .) +
    scale_y_continuous(labels = scales::percent) +
    labs(
      x = "Complaint Type",
      y = "Percent per borough",
      title = "Top 25 overall complaints, by borough",
      caption = "Plot generated by part-1-plots.R"
    ) +
    theme(
      axis.text.x = element_text(angle = 50, hjust = 1),
      panel.grid.minor = element_blank(),
      legend.position = "none",
      legend.title = element_blank()
    )

ggsave(complaints.across.boroughs.plot, height = 9, width = 8,
       units = "in", device = "png", path = ".",
       filename = "complaints-by-borough.png")

